### ISSUE TITLE
Spinner noise when handling `awssso -c` output

### ISSUE THREAD

**Issue by ajkerrigan** [wnkz/aws-sso#10]
This is probably an edge case, so "close/wontfix" is totally cool :).

I often have separate Firefox container tabs open to multiple different AWS accounts. When using the `awssso -c` login option, I pipe the output to `pbcopy` and then paste it in a container tab. A bit hacky but it works. When awssso needs to refresh a token though, all the "Refreshing token" spinner output ends up in the clipboard with the console login URL.

I'm thinking this issue could be avoided by adding `stream=sys.stderr` to the Halo initialization... but I'm not sure if that's desirable in general or just useful to me.

**Comment by wnkz** [comment]
I've spotted this because there was a similar issue when using `credential_process` with `--json` option. I've included the fix as part of a bigger refactor I'm working on but I might push it earlier. In the mean time, you can disable the spinner with `--no-spinner`.

**Comment by ajkerrigan** [comment]
Sounds good, thanks! 👍
