### ISSUE TITLE
Mac Catalina Install keyring error

### ISSUE THREAD

**Issue by maguire007** [wnkz/aws-sso#12]
Getting this error on install on Mac Catalina.  

Collecting keyring<20.0.0,>=19.0.0 (from awssso)
  Could not find a version that satisfies the requirement keyring<20.0.0,>=19.0.0 (from awssso) (from versions: 0.1, 0.2, 0.3, 0.4, 0.5, 0.5.1, 0.6.2, 0.7, 0.7.1, 0.8, 0.8.1, 0.9, 0.9.1, 0.9.2, 0.9.3, 0.10, 0.10.1, 1.0, 1.1, 1.1.1, 1.1.2, 1.2.dev0, 1.2, 1.2.1, 1.2.2, 1.2.3, 1.3, 1.4, 1.5, 1.6, 1.6.1, 2.0, 2.0.1, 2.0.2, 2.0.3, 2.1, 2.1.1, 3.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.1, 3.2, 3.2.1, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 4.0, 4.1, 4.1.1, 5.0, 5.1, 5.2, 5.2.1, 5.3, 5.4, 5.5, 5.5.1, 5.6, 5.7, 5.7.1, 6.0, 6.1, 6.1.1, 7.0, 7.0.1, 7.0.2, 7.1, 7.1.1, 7.1.2, 7.2, 7.3, 7.3.1, 8.0, 8.0.1, 8.1, 8.1.1, 8.2, 8.3, 8.4, 8.4.1, 8.5, 8.5.1, 8.6, 8.6.1, 8.7, 9.0, 9.1, 9.2, 9.2.1, 9.3, 9.3.1, 10.0, 10.0.1, 10.0.2, 10.1, 10.2, 10.3, 10.3.1, 10.3.2, 10.3.3, 10.4.0, 10.5.0, 10.5.1, 10.6.0, 11.0.0, 11.1.0, 12.0.0, 12.0.1, 12.0.2, 12.1.0, 12.2.0, 12.2.1, 13.0.0, 13.1.0, 13.2.0, 13.2.1, 15.0.0, 15.1.0, 15.2.0, 16.0.0, 16.0.1, 16.0.2, 16.1.0, 16.1.1, 17.0.0, 17.1.0, 17.1.1, 18.0.0, 18.0.1)
No matching distribution found for keyring<20.0.0,>=19.0.0 (from awssso)

**Comment by maguire007** [comment]
Go past  the first issue.

pip was using python 2.

It is installed but ran into this Catalina issue https://www.winytips.com/installer-cant-be-opened-because-apple-cannot-check-it-for-malicious-software/
It then ran but threw this error

Traceback (most recent call last):
  File "/usr/local/bin/awssso", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/awssso/cli.py", line 222, in main
    func(args)
  File "/usr/local/lib/python3.7/site-packages/awssso/cli.py", line 79, in configure
    instances = sso.get_instances()
  File "/usr/local/lib/python3.7/site-packages/awssso/ssoclient.py", line 18, in get_instances
    return [i for i in r.json()['result'] if i['applicationName'] == 'AWS Account']
KeyError: 'result'

**Comment by wnkz** [comment]
Hi, everything seems to work fine on macOS 10.15. How is the package installed ? Looks like you're using Python3 from Homebrew + pip ?

Can you provide awssso, Chrome and ChromeDriver versions ? Also the command you ran could help reproduce.
