### ISSUE TITLE
cannot finish configure step

### ISSUE THREAD

**Issue by strannik19** [wnkz/aws-sso#13]
Ran into a problem when configuring awssso:

$ awssso configure                                                                                                                            
[?] URL: https://########.awsapps.com/start/
[?] AWS CLI profile: profile_name
[?] Username: username@domain.com
[?] Password: *****************
Traceback (most recent call last):
  File "/usr/local/bin/awssso", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/awssso/cli.py", line 222, in main
    func(args)
  File "/usr/local/lib/python3.7/site-packages/awssso/cli.py", line 79, in configure
    instances = sso.get_instances()
  File "/usr/local/lib/python3.7/site-packages/awssso/ssoclient.py", line 18, in get_instances
    return [i for i in r.json()['result'] if i['applicationName'] == 'AWS Account']
KeyError: 'result'

**Comment by strannik19** [comment]
`r = self._s.get(f'https://portal.sso.{self._region}.amazonaws.com/instance/appinstances')`
this just gets a 401 error

**Comment by wnkz** [comment]
This likely due to a problem in fetching the token needed for this API. Can you share information about:

- OS
- Python (System, Homebrew, pyenv, ...)
- Installation method (pip, pipenv, pipx, ...)
- Chrome and ChromeDriver versions

**Comment by strannik19** [comment]
macOS 10.14.6
Homebrew Python 3.7.4
installation method: pip
chromedriver: 77.0.3865.40
Chrome: 77.0.3865.120

**Comment by strannik19** [comment]
the awssso authn-token entry exists in my keychain and its populated

**Comment by wnkz** [comment]
Does this happen **all the time** or was this a one time error ? In what region is AWS SSO deployed ?

You can specify this with `--region` option or with environment variables `AWSSSO_REGION`, `AWS_DEFAULT_REGION` otherwise it defaults to `eu-west-1`

**Comment by strannik19** [comment]
when I directly pass in --region it works. thanks. haven't tried the env variables yet.
I was assuming this would come from the profile that is being used, as I have many different profiles in different regions, and always having to specify which one can be hard to remember.
any which way, thanks, closing this issue!

**Comment by wnkz** [comment]
@strannik19 yes, in the current version there is a default value to the `region` parameter which overrides the one in the configuration ; this will get fixed in the next release.
