### ISSUE TITLE
no checkbox when entering mfa code. cannot login

### ISSUE THREAD

**Issue by convoi** [wnkz/aws-sso#18]
when i open my sso start page, enter my credentials there is no checkbox on the mfa code entering page.
since ssodriver.py always wants to find this element, it fails.
when i move that line to the "if trusted_device" branch, and default the trusted device to False, i can proceed.
disclaimer: I use the (standard?) aws sso mfa way where aws sends us emails with a code.

**Comment by wnkz** [comment]
I don't think I'll be making new changes to this tool since AWS announced the feature in awscliv2 ; check this out https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sso.html
